shiftiy/config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  resources :shifts
  resources :stores
  resources :staffs

  post "shifts/events" => "shifts#get_events"
  post "shifts/submit" => "shifts#submit"


end

shiftiy/app/models/shift.rb
class Shift < ActiveRecord::Base
end

shiftiy/app/models/staff.rb
class Staff < ActiveRecord::Base
end

shiftiy/app/models/store.rb
class Store < ActiveRecord::Base
end

shiftiy/app/models/store_staff.rb
class StoreStaff < ActiveRecord::Base
end

shiftiy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

shiftiy/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @message = "welcome to shiftiy"
  end
end

shiftiy/app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit

  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)
    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_events
    shift_id = params[:shift_id]
    # load data by shift_id
    #@shift = Shift.find(2)
    render json: [
      # {
      #   title: 'From table',
      #   start: @shift.date,
      # },
      {
        title: 'All Day Event',
        start: '2016-01-01',
      },
      {
        title: 'All Day Event 2',
        start: '2016-01-03',
      },
      {
        title: 'All Day Event 3',
        start: '2016-01-05',
      }
    ]
  end

  def submit
    # JSON save
    # params[:id][]
    render json: {tukky: "a"}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:store_staff_id, :date, :start_time, :end_time, :rest_time)
    end
end

shiftiy/app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :email, :position_id)
    end
end

shiftiy/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :email, :image_url, :open_time, :close_time, :tel, :address)
    end
end

shiftiy/app/helpers/application_helper.rb
module ApplicationHelper
end

shiftiy/app/helpers/home_helper.rb
module HomeHelper
end

shiftiy/app/helpers/shifts_helper.rb
module ShiftsHelper
end

shiftiy/app/helpers/staffs_helper.rb
module StaffsHelper
end

shiftiy/app/helpers/stores_helper.rb
module StoresHelper
end

shiftiy/app/views/home/top.html.erb
  <h1><%= @message %></h1>

shiftiy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Shiftiy</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="css/simple-sidebar.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Shiftiy
                    </a>
                </li>
                <h5>店舗</h5>
                <li><%= link_to "店舗情報編集", stores_path %></li>
                <h5>店員</h5>
                <li><%= link_to "新規店員追加", staffs_path %></li>
                <li><%= link_to "店員編集", staffs_path %></li>
                <h5>シフト</h5>
                <li><%= link_to "パターン作成", shifts_path %></li>
                <li><%= link_to "シフト整理", shifts_path %></li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
</body>

</html>

shiftiy/app/views/shifts/_form.html.erb
<%= form_for(@shift) do |f| %>
  <% if @shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% @shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_staff_id %><br>
    <%= f.number_field :store_staff_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :rest_time %><br>
    <%= f.time_select :rest_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shiftiy/app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

shiftiy/app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shifts</h1>

<table>
  <thead>
    <tr>
      <th>Store staff</th>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Rest time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.store_staff_id %></td>
        <td><%= shift.date %></td>
        <td><%= shift.start_time %></td>
        <td><%= shift.end_time %></td>
        <td><%= shift.rest_time %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

shiftiy/app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form' %>

<div id="calendar">

</div>

<button type="button" name="button" id="save">提出する</button>

<%= link_to 'Back', shifts_path %>

shiftiy/app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store staff:</strong>
  <%= @shift.store_staff_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @shift.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @shift.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @shift.end_time %>
</p>

<p>
  <strong>Rest time:</strong>
  <%= @shift.rest_time %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>

shiftiy/app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :position_id %><br>
    <%= f.number_field :position_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shiftiy/app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

shiftiy/app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.email %></td>
        <td><%= staff.position_id %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

shiftiy/app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

shiftiy/app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staff.email %>
</p>

<p>
  <strong>Position:</strong>
  <%= @staff.position_id %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>

shiftiy/app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :open_time %><br>
    <%= f.time_select :open_time %>
  </div>
  <div class="field">
    <%= f.label :close_time %><br>
    <%= f.time_select :close_time %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shiftiy/app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

shiftiy/app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Image url</th>
      <th>Open time</th>
      <th>Close time</th>
      <th>Tel</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.email %></td>
        <td><%= store.image_url %></td>
        <td><%= store.open_time %></td>
        <td><%= store.close_time %></td>
        <td><%= store.tel %></td>
        <td><%= store.address %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

shiftiy/app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

shiftiy/app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @store.email %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @store.image_url %>
</p>

<p>
  <strong>Open time:</strong>
  <%= @store.open_time %>
</p>

<p>
  <strong>Close time:</strong>
  <%= @store.close_time %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @store.tel %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>