autoshift/config/routes.rb
Rails.application.routes.draw do
  root 'shifts#index'
  resources :stores
  resources :patterns
  resources :shifts
  resources :positions
  resources :staffs

end

autoshift/app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :shift
end

autoshift/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :set_pattern, except: [:update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    def set_pattern
      @patterns = Pattern.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :email, :tel, :address)
    end
end

autoshift/app/helpers/stores_helper.rb
module StoresHelper
end

autoshift/app/views/stores/_form.html.slim
= form_for @store, :html => { :class => "form-horizontal store" } do |f|
  - if @store.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        h3.panel-title
          = pluralize(@store.errors.count, "error")
          |  prohibited this store from being saved:
      .panel-body
        ul
          - @store.errors.full_messages.each do |msg|
            li
              = msg
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    / =f.error_span(:name)
  .form-group
    = f.label :email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email, :class => 'form-control'
    / =f.error_span(:email)
  .form-group
    = f.label :tel, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :tel, :class => 'form-control'
    / =f.error_span(:tel)
  .form-group
    = f.label :address, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :address, :class => 'form-control'
    / =f.error_span(:address)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")),
                     stores_path, :class => 'btn btn-default'

autoshift/app/views/stores/edit.html.slim
- model_class = Store
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

autoshift/app/views/stores/index.html.slim
- model_class = Store
.page-header
  h1
    =t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th
        = model_class.human_attribute_name(:id)
      th
        = model_class.human_attribute_name(:name)
      th
        = model_class.human_attribute_name(:email)
      th
        = model_class.human_attribute_name(:tel)
      th
        = model_class.human_attribute_name(:address)
      th
        = model_class.human_attribute_name(:created_at)
      th
        =t '.actions', :default => t("helpers.actions")
  tbody
    - @stores.each do |store|
      tr
        td
          = link_to store.id, store_path(store)
        td
          = store.name
        td
          = store.email
        td
          = store.tel
        td
          = store.address
        td
          =l store.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")),
                                 edit_store_path(store), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")),
                                 store_path(store),
                                 :method => :delete,
                                 :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                 :class => 'btn btn-xs btn-danger'
= link_to t('.new', :default => t("helpers.links.new")),
             new_store_path,
             :class => 'btn btn-primary'

autoshift/app/views/stores/new.html.slim
- model_class = Store
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

autoshift/app/views/stores/show.html.slim
- model_class = Store
.page-header
  h1
    =t '.title', :default => model_class.model_name.human.titleize
dl.dl-horizontal
  dt
    strong
      = model_class.human_attribute_name(:name)
      | :
  dd
    = @store.name
  dt
    strong
      = model_class.human_attribute_name(:email)
      | :
  dd
    = @store.email
  dt
    strong
      = model_class.human_attribute_name(:tel)
      | :
  dd
    = @store.tel
  dt
    strong
      = model_class.human_attribute_name(:address)
      | :
  dd
    = @store.address
= link_to t('.back', :default => t("helpers.links.back")),
               stores_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")),
               edit_store_path(@store), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")),
               store_path(@store),
               :method => 'delete',
               :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
               :class => 'btn btn-danger'