autoshift/config/routes.rb
Rails.application.routes.draw do
  root 'shifts#index'
  resources :stores
  resources :patterns
  resources :shifts
  resources :positions
  resources :staffs

end

autoshift/app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :shift
end

autoshift/app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  before_action :set_pattern, except: [:update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    def set_pattern
      @patterns = Pattern.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :email, :position_id, :priority)
    end
end

autoshift/app/helpers/staffs_helper.rb
module StaffsHelper
end

autoshift/app/views/staffs/_form.html.slim
= form_for @staff, :html => { :class => "form-horizontal staff" } do |f|
  - if @staff.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        h3.panel-title
          = pluralize(@staff.errors.count, "error")
          |  prohibited this staff from being saved:
      .panel-body
        ul
          - @staff.errors.full_messages.each do |msg|
            li
              = msg
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    / =f.error_span(:name)
  .form-group
    = f.label :email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email, :class => 'form-control'
    / =f.error_span(:email)
  .form-group
    = f.label :position_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :position_id, :class => 'form-control'
    / =f.error_span(:position_id)
  .form-group
    = f.label :priority, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :priority, :class => 'form-control'
    / =f.error_span(:priority)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")),
                      staffs_path, :class => 'btn btn-default'

autoshift/app/views/staffs/edit.html.slim
- model_class = Staff
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

  h1 aaaa

autoshift/app/views/staffs/index.html.slim
- model_class = Staff
.page-header
  h1
    =t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th
        = model_class.human_attribute_name(:id)
      th
        = model_class.human_attribute_name(:name)
      th
        = model_class.human_attribute_name(:email)
      th
        = model_class.human_attribute_name(:position_id)
      th
        = model_class.human_attribute_name(:priority)
      th
        = model_class.human_attribute_name(:created_at)
      th
        =t '.actions', :default => t("helpers.actions")
  tbody
    - @staffs.each do |staff|
      tr
        td
          = link_to staff.id, staff_path(staff)
        td
          = staff.name
        td
          = staff.email
        td
          = staff.position_id
        td
          = staff.priority
        td
          =l staff.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")),
                                edit_staff_path(staff), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")),
                                 staff_path(staff),
                                 :method => :delete,
                                 :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                                 :class => 'btn btn-xs btn-danger'
= link_to t('.new', :default => t("helpers.links.new")),
             new_staff_path,
             :class => 'btn btn-primary'

autoshift/app/views/staffs/new.html.slim
- model_class = Staff
.page-header
  h1
    =t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

autoshift/app/views/staffs/show.html.slim
/ - model_class = Staff
/ .page-header
/   h1
/     =t '.title', :default => model_class.model_name.human.titleize
/ 
/ dl.dl-horizontal
/   dt
/     strong
/       = model_class.human_attribute_name(:name)
/       | :
/   dd
/     = @staff.name
/   dt
/     strong
/       = model_class.human_attribute_name(:email)
/       | :
/   dd
/     = @staff.email
/   dt
/     strong
/       = model_class.human_attribute_name(:position_id)
/       | :
/   dd
/     = @staff.position_id
/   dt
/     strong
/       = model_class.human_attribute_name(:priority)
/       | :
/   dd
/     = @staff.priority
/ = link_to t('.back', :default => t("helpers.links.back")),
/                staffs_path, :class => 'btn btn-default'
/ = link_to t('.edit', :default => t("helpers.links.edit")),
/                edit_staff_path(@staff), :class => 'btn btn-default'
/ = link_to t('.destroy', :default => t("helpers.links.destroy")),
/                staff_path(@staff),
/                :method => 'delete',
/                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
/                :class => 'btn btn-danger'
/ 
.calender_zone
  h1 シフト提出
  
  head
    javascript:
      | var CLIENT_ID = '671708083576-3iluvpvhekdv0linff5196beq280q7mv.apps.googleusercontent.com';
      | var SCOPES = ["https://www.googleapis.com/auth/calendar.readonly"];
      | function checkAuth() {
        | gapi.auth.authorize(
          | {
            | 'client_id': CLIENT_ID,
            | 'scope': SCOPES.join(' '),
            | 'immediate': true
          | }, handleAuthResult);
      | }
      
      | function handleAuthResult(authResult) {
        | var authorizeDiv = document.getElementById('authorize-div');
        | if (authResult && !authResult.error) {
          | authorizeDiv.style.display = 'none';
          | loadCalendarApi();
        | } else {
          | authorizeDiv.style.display = 'inline';
        | }
      | }
      
      | function handleAuthClick(event) {
        | gapi.auth.authorize(
          | {client_id: CLIENT_ID, scope: SCOPES, immediate: false},
          | handleAuthResult);
        | return false;
      | }
      
      | function loadCalendarApi() {
        | gapi.client.load('calendar', 'v3', listUpcomingEvents);
      | }
      
      | function listUpcomingEvents() {
        | var request = gapi.client.calendar.events.list({
          | 'calendarId': 'primary',
          | 'timeMin': (new Date()).toISOString(),
          | 'showDeleted': false,
          | 'singleEvents': true,
          | 'maxResults': 10,
          | 'orderBy': 'startTime'
        | });
        
        | request.execute(function(resp) {
          | var events = resp.items;
          | appendPre('Upcoming events:');

          | if (events.length > 0) {
            | for (i = 0; i < events.length; i++) {
              | var event = events[i];
              | var when = event.start.dateTime;
              | if (!when) {
                | when = event.start.date;
              | }
              | appendPre(event.summary + ' (' + when + ')')
            | }
          | } else {
            | appendPre('No upcoming events found.');
          | }

        | });
      | }

      | function appendPre(message) {
        | var pre = document.getElementById('output');
        | var textContent = document.createTextNode(message + '\n');
        | pre.appendChild(textContent);
      | }
    script src="https://apis.google.com/js/client.js?onload=checkAuth" 



  body
    #authorize-div style=("display: none") 
      span Authorize access to Google Calendar API
      /! Button for the user to click to initiate auth sequence
      button#authorize-button onclick="handleAuthClick(event)" 
        | Authorize
    pre#output
    iframe frameborder="0" height="600" scrolling="no" src="https://calendar.google.com/calendar/embed?src=8i62evmesv0bgpggpa10e1ecps%40group.calendar.google.com&ctz=Asia/Tokyo" style=("border: 0") width="800" 
  
  